authentication/urls.py
from django.urls import path 
from .views import * 


app_name = 'authentication'

urlpatterns = [ 
    path('', AuthIndexView.as_view(), name='index'),
    path('login/', AuthLoginView.as_view(), name='login'),
    path('logout/', AuthLogoutView.as_view(), name='logout'),
    path('password_change/', AuthPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', AuthPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', AuthPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', AuthPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', AuthPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', AuthPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', AuthRegisterView.as_view(), name='register'),
    path('register/done/', AuthRegisterDoneView.as_view(), name='register_done'),
    path('profile/', AuthProfileView.as_view(), name='profile'),
] 

authentication/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib import auth
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class User(auth.models.AbstractBaseUser, auth.models.PermissionsMixin):
	username = models.CharField(max_length=100, unique=True)
	first_name = models.CharField(max_length=100, blank=True)
	last_name = models.CharField(max_length=100, blank=True)
	email = models.EmailField(blank=True)
	is_staff = models.BooleanField(default=False,)
	is_active = models.BooleanField(default=True)
	date_joined = models.DateTimeField(default=timezone.now)

	objects = auth.models.UserManager()

	EMAIL_FIELD = 'email'
	USERNAME_FIELD = 'username'
	# REQUIRED_FIELDS = ['email']

	def __str__(self): return self.username


class Profile(models.Model):

	class Gender(models.TextChoices):
		MALE = 'Male', _('Male')
		FEMALE = 'Female', _('Female')
		UNKNOWN = 'Unknown', _('Unknown')

	user = models.OneToOneField(User, on_delete=models.CASCADE)
	gender = models.CharField(max_length=100, blank=True, choices=Gender.choices)
	phone = models.CharField(max_length=100, blank=True, null=True)
	age = models.IntegerField(blank=True, null=True)
	address = models.TextField(blank=True, null=True)
	birthday = models.DateField(max_length=10, blank=True, null=True)
	avatar = models.ImageField(default='images/avatar_default_male.jpg', upload_to='images')

	def __str__(self): return f"Profile of {self.user.username}"

	def save(self, *args, **kwargs):
		if self.gender == 'Female': self.avatar = 'images/avatar_default_female.jpg'
		return super().save(*args, **kwargs)

def create_user_profile(sender, instance, created, **kwargs):
	if created: Profile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()

models.signals.post_save.connect(create_user_profile, sender=User)
models.signals.post_save.connect(save_user_profile, sender=User)

authentication/forms.py
from django import forms
from django.contrib.auth.forms import *
from django.contrib.auth import get_user_model
from django.core import exceptions
from django.utils.translation import gettext_lazy as _


class AuthForm(AuthenticationForm):
    error_messages = { 'invalid_login': _('Invalid login'), 'inactive': _('Inactive'), }
    def confirm_login_allowed(self, user):
        if not user.is_active: raise exceptions.ValidationError(_('User inactive'), code='inactive')

class RegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email')
        field_classes = {'username': UsernameField}
        widgets = {'email': forms.EmailInput(attrs={'required': True})}

authentication/views.py
from django.shortcuts import render, HttpResponse, redirect 
from django.urls import path, include, URLPattern, URLResolver, reverse_lazy, reverse
from django.views import generic
from django.contrib.auth import get_user_model, backends
from django.contrib.auth.views import *
from django.contrib.auth.mixins import *
from django.utils.translation import gettext_lazy as _

from authentication.models import Profile
from authentication.forms import *

inc_path = path('authentication/', include('authentication.urls'))


class AuthModelBackend(backends.ModelBackend):
    def user_can_authenticate(self, user):
        return True

class AuthIndexView(generic.TemplateView):
    template_name = 'authentication/index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        urlconf = __import__('apps.authentication.urls', {}, {}, [''])
        def list_urls(lis, acc=None):
            acc = [] if acc is None else acc
            if not lis: return None
            l = lis[0]
            if isinstance(l, URLPattern): yield acc + [str(l.pattern)]
            elif isinstance(l, URLResolver): yield from list_urls(l.url_patterns, acc + [str(l.pattern)])
            yield from list_urls(lis[1:], acc)
        url_list = []
        for p in list_urls(urlconf.urlpatterns, ['']):
            url_list.append(''.join(p)) 
        context['url_list'] = url_list
        return context
    
class AuthLoginView(LoginView):
    authentication_form = AuthForm
    template_name = 'authentication/login.html'
    login_url = reverse_lazy('authentication:login')
    next_page = reverse_lazy('authentication:index')
    redirect_authenticated_user = True # If it is false, authenticated_user is still access to login

class AuthLogoutView(LogoutView):
    # template_name = 'authentication/logged_out.html'
    next_page = reverse_lazy('authentication:login') # if not default render to template

class AuthPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'authentication/password_change_form.html'
    success_url = reverse_lazy('authentication:password_change_done')

class AuthPasswordChangeDoneView(LoginRequiredMixin, PasswordChangeDoneView):
    template_name = 'authentication/password_change_done.html'

class AuthPasswordResetView(PasswordResetView):
    template_name = 'authentication/password_reset_form.html'
    success_url = reverse_lazy('authentication:password_reset_done')
    from_email = 'system@sys.com'
    email_template_name = 'authentication/password_reset_email.html'
    subject_template_name = 'authentication/password_reset_subject.txt'

class AuthPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'authentication/password_reset_done.html'

class AuthPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'authentication/password_reset_confirm.html'
    success_url = reverse_lazy('authentication:password_reset_complete')

class AuthPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'authentication/password_reset_complete.html'

class AuthRegisterView(generic.FormView):
    template_name = 'authentication/register.html'
    form_class = RegisterForm
    def form_valid(self, form):
        new_user = get_user_model().objects.create_user(
            username = form.cleaned_data['username'],
            password = form.cleaned_data['password1'],
            email = form.cleaned_data['email'],
        )
        url = f"{reverse('authentication:register_done')}?username={new_user.username}"
        return redirect(url)

class AuthRegisterDoneView(generic.TemplateView):
    template_name = 'authentication/register_done.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.GET.get('username')
        return context
    
class AuthProfileView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'authentication/profile.html'

authentication/templates/index.html
{% for url in url_list %} <div> -- <a href="{{ url }}" > {% if url == '' %} current {% else %} {{ url }} {% endif %} </a> </div> {% endfor %}

authentication/templates/login.html
<form method="post"> {% csrf_token %} {{ form.as_p }} <input type="submit" value="Login" /> </form>

authentication/templates/password_change_done.html
PASSWORD_CHANGE_DONE

authentication/templates/password_change_form.html
<form method="post"> {% csrf_token %} {{ form.as_p }} <input type="submit" value="change"> </form>

authentication/templates/password_reset_complete.html
PASSWORD_RESET_COMPLETE

authentication/templates/password_reset_confirm.html
<form method="post"> {% csrf_token %} {{ form.as_p }} <input type="submit" value="reset"> </form>

authentication/templates/password_reset_done.html
CHECK_EMAIL_PLEASE

authentication/templates/password_reset_email.html
{% load i18n %}

{% blocktrans %}Greetings{% endblocktrans %} {% if user.get_full_name %}{{ user.get_full_name }}{% else %}{{ user }}{% endif %},

{% blocktrans %}
You are receiving this email because you (or someone pretending to be you)
requested that your password be reset on the {{ domain }} site. If you do not
wish to reset your password, please ignore this message.
{% endblocktrans %}

{% blocktrans %}
To reset your password, please click the following link, or copy and paste it
into your web browser:
{% endblocktrans %}

<a rel="noreferrer" href="{{ protocol }}://{{ domain }}{% url 'authentication:password_reset_confirm' uid token %}">
  {{ protocol }}://{{ domain }}{% url 'authentication:password_reset_confirm' uid token %}
</a>

{% blocktrans %}Your username, in case you've forgotten:{% endblocktrans %} {{ user.get_username }}


{% blocktrans %}Best{% endblocktrans %},
{{ site_name }} {% blocktrans %}Management{% endblocktrans %}


{# This is used by django.contrib.auth #}

authentication/templates/password_reset_form.html
<form method="post"> {% csrf_token %} {{ form.as_p }} <input type="submit" value="reset"> </form>

authentication/templates/profile.html
{{ user.username }} | {{ user.email }} | {{ user.date_joined | date:'d-m-Y' }} |
<a href="{% url 'authentication:logout' %}">logout</a> |
<a href="{% url 'authentication:profile_update' user.id %}">update</a> |
<a href="{% url 'authentication:password_change' %}">password-change</a>

authentication/templates/register.html
<form method="post"> {% csrf_token %} {{ form.as_p }} <input type="submit" value="register"> </form>

authentication/templates/register_done.html
REGISTER_DONE: {{ username }}